language: java
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
script:
  - mvn integration-test
after_success:
  - mvn clean -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID cobertura:cobertura coveralls:report
